# Generated by Django 2.2.13 on 2021-02-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block_structure', '0019_orablockstructure_ungraded'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiBlockInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(db_index=True, max_length=255)),
                ('block_id', models.CharField(db_index=True, max_length=255)),
                ('hash_id', models.CharField(db_index=True, max_length=255)),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'api_block_info',
                'unique_together': {('course_id', 'block_id')},
            },
        ),
    ]
